name=ESP32 BLE Combo Keyboard Mouse
version=0.2.0
author=T-vK, uuhc
maintainer=uuhc <uuhc76@outlook.com>
sentence=Bluetooth LE Combo Keyboard Mouse library for the ESP32.
paragraph=Bluetooth LE Combo Keyboard Mouse library for the ESP32.
category=Communication
url=https://github.com/uuhc/ESP32-BLE-Combo
architectures=esp32
